
[cn]
quick_mode = "极速模式"
copy_mode = "自定义模式"
mode_select_msg = "本次转存任务您选择了 ┋replace┋" #replace==待替换占位符
request_share_link = "请输入 Google Drive 分享链接 或 分享ID"
request_dst_target = "请选择文件保存位置"
is_cover = "覆盖"
not_cover = "返回"
is_cover_quick_msg = "QUICK\\_MODE 已存在指定快捷路径\n是否需要覆盖"
insert_quick_success = "QUICK\\_MODE 指定快捷路径已设置成功"
modify_quick_success = "QUICK\\_MODE 指定快捷路径已更新成功"
null_fav_quick = "未设置QUICK\\_MODE 转存目录\n请设置后再次尝试"
null_fav = "未设置COPY\\_MODE 转存目录\n请设置后再次尝试"
ready_to_task = "转存任务准备中..."
doing = "正在执行任务"
done = "任务成功"
current_task_id = "任务编号 : "
task_start_time = "任务开始时间 : "
task_finished_time = "任务结束时间 : "
task_files_size = "文件总大小 : "
task_files_num = "任务文件数 : "
task_status = "任务状态:"
elapsed_time = "总耗时 : "
cancel_msg = "欢迎再次使用 iCopy"
get_quick_count_invaild = "quick 模式下的快捷目录只允许存在一个"
get_multi_fav_error = "请根据'/set'规则提交目录设置"
get_single_fav_error = "请根据'/set rule'规则发送命令"
get_multi_in_single = "多行设置请使用 '/set'"
task_src_info = "[任务目标]:"
task_dst_info = "[转存地址]:"
is_set_dedupe = "设置收藏夹遇到错误"
set_fav_success = "设置收藏夹成功"
delete_fav_success = "删除收藏夹成功"
delete_quick_success = "QUICK_MODE 指定快捷路径已删除"
show_fav_list = "下列为已设置的收藏夹"
show_fav_list_null = "未设置任何收藏夹"
is_restarting = "iCopy机器人正在重启...\n请在30秒后开始使用"

[eng]
quick_mode = "QUICK MODE"
copy_mode = "COPY MODE"
mode_select_msg = "┋replace┋ has be choosen" #replace==symbolic placeholder
request_share_link = "Pls input Shared_Link or Shared_ID"
request_dst_target = "Please select the destination path for the task"
is_cover = "Cover it"
not_cover = "Cancel"
is_cover_quick_msg = "QUICK\\_MODE The specified directory already exists\nDo you need to cover it?"
insert_quick_success = "QUICK\\_MODE specified path is setted successfully"
modify_quick_success = "QUICK\\_MODE specified path is renewed successfully"
null_fav_quick = "QUICK\\_MODE directory is not set\nPlease try again after setting"
null_fav = "COPY\\_MODE directory is not set\nPlease try again after setting"
ready_to_task = "Now is Ready to Task..."
doing = "Transferring"
done = "Done"
current_task_id = "task id : "
task_start_time = "Task start time : "
task_finished_time = "Task end time : "
task_files_size = "Total file size : "
task_files_num = "Task file num : "
task_status = "task_status:"
elapsed_time = "Elapsed Time : "
cancel_msg = "Welcome to enjoy with iCopy again"
get_quick_count_invaild = "Only ONE Dst ID can be specified under quick mode"
get_multi_fav_error = "pls submit DST ID according '/set'"
get_single_fav_error = "pls submit single DST ID according '/set rule'"
get_multi_in_single = "pls use '/set' while modify multi DST IDs"
task_src_info = "[Resource From]:"
task_dst_info = "[Transfer To]:"
is_set_err = "SET FAV ERROR"
set_fav_success = "set Favorites success"
delete_fav_success = "Favorites deleted successfully"
delete_quick_success = "QUICK\\_MODE specified path is deleted successfully"
show_fav_list = "The following are favorites that have been set"
show_fav_list_null = "Favorites are not set"
is_restarting = "iCopy is restarting...\nPlease start using in 30 seconds"

[jp]
quick_mode = "「クイックモード」"
copy_mode = "「カスタマイズ　モード」"
mode_select_msg = "┋replace┋が選択されました" #replace==置き換え指示記号
request_share_link = "共有リンクまたは共有IDを入力してください"
request_dst_target = "ファイルの保存場所を選択してください"
is_cover = "カバー"
not_cover = "キャンセル"
is_cover_quick_msg = "QUICK_MODE指定されたフォルダーはすでに存在します\n新しいフォルダで上書きしますか?"
insert_quick_success = "QUICK_MODEで指定されたフォルダーが正常に設定されました"
modify_quick_success = "QUICK_MODEで指定されたフォルダーが更新されました"
null_fav_quick = "QUICK\\_MODEフォルダーが設定されていません\n設定後にもう一度お試しください"
null_fav = "COPY\\_MODEフォルダーが設定されていません\n設定後にもう一度お試しください"
ready_to_task = "任務準備中..."
doing = "タスク実行中"
done = "任務成功"
current_task_id = "タスク番号 : "
task_start_time = "タスク開始時刻 : "
task_finished_time = "タスク終了時間 : "
task_files_size = "ファイルサイズ : "
task_files_num = "タスクファイル数 : "
task_status = "タスク状態:"
elapsed_time = "合計時間 : "
cancel_msg = "再びiCopyへようこそ"
get_quick_count_invaild = "「クイックモード」で一つフォルダーしか指定されることができない"
get_multi_fav_error = "'/set'にルールをよって、フォルダーのIDを入力してください"
get_single_fav_error = "'/set rule'にルールをよって、フォルダーのIDを入力してください"
get_multi_in_single = "複数のフォルダーを設定する場合は、「/set」コマンドを使用してください"
task_src_info = "[任務目標]:"
task_dst_info = "[保存場所]:"
is_set_dedupe = "お気に入りを設定するとエラーが発生します"
set_fav_success = "お気に入りを設定しました"
delete_fav_success = "お気に入り削除に成功"
delete_quick_success = "QUICK_MODEで指定されたフォルダーが削除されました"
show_fav_list = "以下は既設のお気に入りである"
show_fav_list_null = "お気に入りは設定いない"
is_restarting = "iCopyが再起動しています...\n30秒後に使用を開始してください"